"""
DevOps War Room Environment - Data Models
Pydantic models for OpenEnv compliance
"""

from typing import Dict, List, Optional, Any
from enum import Enum
from pydantic import BaseModel, Field

DEFAULT_DISPLAY_SCORE = 0.1


class ActionType(str, Enum):
    """Structured action types for SRE intervention"""
    QUERY_LOGS = "query_logs"
    QUERY_METRICS = "query_metrics"
    TRACE_REQUEST = "trace_request"
    RESTART_SERVICE = "restart_service"
    ROLLBACK_DEPLOYMENT = "rollback_deployment"
    SCALE_SERVICE = "scale_service"
    PRIORITIZE_INCIDENT = "prioritize_incident"
    RESOLVE_INCIDENT = "resolve_incident"


class ServiceName(str, Enum):
    """Microservices in the system"""
    AUTH = "auth"
    PAYMENTS = "payments"
    DB = "db"
    CACHE = "cache"
    API_GATEWAY = "api_gateway"


class MetricType(str, Enum):
    """Observable metrics"""
    LATENCY = "latency"
    ERROR_RATE = "error_rate"
    CPU = "cpu"
    MEMORY = "memory"
    CONNECTION_COUNT = "connection_count"
    QUEUE_DEPTH = "queue_depth"


class Action(BaseModel):
    """
    Action taken by the agent in the war room.
    Structured to reflect real SRE debugging workflows.
    """
    action_type: ActionType = Field(..., description="Type of action")
    service: Optional[ServiceName] = Field(None, description="Target service")
    metric: Optional[MetricType] = Field(None, description="Metric to query")
    trace_id: Optional[str] = Field(None, description="Trace ID for tracing")
    replicas: Optional[int] = Field(None, description="Number of replicas to scale")
    version: Optional[str] = Field(None, description="Version to rollback to")
    incident_id: Optional[str] = Field(None, description="Incident to prioritize/resolve")
    root_cause: Optional[str] = Field(None, description="Identified root cause")

    class Config:
        json_schema_extra = {
            "example": {
                "action_type": "query_logs",
                "service": "api_gateway",
                "metric": None,
                "trace_id": None,
                "replicas": None,
                "version": None,
                "incident_id": None,
                "root_cause": None
            }
        }


class ServiceStatus(BaseModel):
    """Real-time service health status"""
    name: ServiceName
    is_healthy: bool
    latency_ms: float
    error_rate: float
    cpu_percent: float
    memory_percent: float
    uptime_seconds: int


class Alert(BaseModel):
    """Alert generated by monitoring system"""
    alert_id: str
    service: ServiceName
    severity: str  # "critical", "warning", "info"
    message: str
    timestamp: int  # step number
    is_resolved: bool = False


class LogEntry(BaseModel):
    """Log entry from service"""
    timestamp: int
    service: ServiceName
    level: str  # "ERROR", "WARN", "INFO"
    message: str
    trace_id: Optional[str] = None
    is_relevant: bool = True  # False for noisy logs


class Observation(BaseModel):
    """
    Observable state of the war room.
    What the agent can see at each step.
    """
    alerts: List[Alert] = Field(default_factory=list, description="Active alerts")
    services_status: List[ServiceStatus] = Field(
        default_factory=list, description="Status of all services"
    )
    recent_logs: List[LogEntry] = Field(default_factory=list, description="Partial log view")
    active_incidents: List[str] = Field(
        default_factory=list, description="IDs of active incidents"
    )
    metrics_summary: Dict[str, Dict[str, float]] = Field(
        default_factory=dict, description="Summary of recent metrics"
    )
    current_step: int = Field(0, description="Current step number")
    damage_score: float = Field(
        DEFAULT_DISPLAY_SCORE,
        description="System damage, emitted as a score strictly between 0.0 and 1.0",
    )
    available_actions: List[str] = Field(
        default_factory=lambda: [a.value for a in ActionType],
        description="Available action types"
    )


class Reward(BaseModel):
    """Reward and metadata from step"""
    value: float = Field(..., description="Reward value (-1.0 to 1.0)")
    components: Dict[str, float] = Field(
        default_factory=dict,
        description="Breakdown of reward components"
    )
    info: Dict[str, Any] = Field(default_factory=dict, description="Metadata")


class TaskDefinition(BaseModel):
    """Definition of a task variant"""
    task_id: str
    difficulty: str  # "easy", "medium", "hard"
    name: str
    description: str
    max_steps: int
    num_incidents: int
    has_cascading_failures: bool
    num_misleading_logs: int
    grader: Optional[Dict[str, Any]] = None


class State(BaseModel):
    """Complete environment state (partially observable)"""
    # Observable
    alerts: List[Alert]
    services_status: List[ServiceStatus]
    recent_logs: List[LogEntry]
    active_incidents: List[str]
    metrics_summary: Dict[str, Dict[str, float]]
    current_step: int
    damage_score: float

    # Hidden
    root_causes: Dict[str, str]
    dependency_graph: Dict[ServiceName, List[ServiceName]]
    incident_history: List[Dict[str, Any]]
    all_logs: List[LogEntry]
    true_metrics: Dict[str, Dict[str, float]]

    # Task state
    task_config: TaskDefinition
    resolved_incidents: List[str]
    incorrect_resolutions: List[str]
    prioritized_incidents: List[str] = Field(default_factory=list)
